# Site settings
title: Nicolas Vogt
description: Nicolas Vogt's Portfolio
# baseurl: "/portfolio" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Nicolas Vogt
user_description: I'm a passionate programmer, who enjoys the implementation of the latest web development tools and concurrently learning the intricacies of programming languages. Stemming from my love of human languages and time spent learning abroad, I am excited by the challenges presented by new environments with new people. 
user_title: Full Stack Web Developer
email: nicolasjvogt@gmail.com
twitter_username: NicVogt
github_username:  vogtn
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
